name: AboutMe
version: 1.1
main: mymods.AboutMe

commands:
  myname:
    description: What's my name?
  mystats:
    description: What's my stats?
  ouch:
    description: Decrease food level.
  yammie:
    description: Increase food level.
